# Ruff configuration file
# https://docs.astral.sh/ruff/rules/

target-version = "py313"

[lint]
select = ["ALL"]
ignore = [
    "COM812", # Missing trailing comma, conflict with the formatter
    "D104",   # Missing docstring in public package
    "D203",   # 1 blank line required before class docstring
    "D213",   # Multi-line docstring summary should start at the second line
    "D413",   # Missing blank line after last section
    "FIX002", # Line contains TODO, consider resolving the issue
    "RET504", # Unnecessary assignment to `value` before `return` statement
    "TD002",  # Missing author in TODO
    "TD003",  # Missing issue link for this TODO
]

[lint.per-file-ignores]
"*.ipynb" = [
    "ERA001", # Found commented-out code
    "F401", # unused import
    "T20",  # print found
]
"tests/*" = [
    "ARG001", # Unused function argument: mocks and similar
    "INP001", # File `tests/...` is part of an implicit namespace package. Add an `__init__.py`. Causes a bug.
    "PLR2004", # Magic value used in comparison, consider replacing `NUM` with a constant variable
    "S101",   # Use of assert detected
]
"meta/*" = [
    "INP001", # Implicit namespace package
    "T20",    # print found
]

[lint.pylint]
max-args = 10

[lint.isort]
force-sort-within-sections = true
force-single-line = true
